version: '3'
services:
  gotenberg:
    image: gotenberg/gotenberg:7
    networks:
      - osmond
    expose:
      - 3000

  osmond:
    image: mosswill/osmond:latest
    depends_on:
      - gotenberg
    networks:
      - osmond
      - global
    expose:
      - 80
    environment:
      SERVER_HOST: "https://your-domain.tld"
      SERVER_PORT: "80"
      SERVER_SECRET: "<PLACEHOLDER>"

      SERVER_PROXIED: "TRUE"
      SERVER_PROXY_PORT: "443"

      DOWNLOAD_USER_AGENT: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
      DOWNLOAD_CONVERT_PDF: "TRUE"
      DOWNLOAD_FORCE_READER: "FALSE"

      SMTP_HOST: "<PLACEHOLDER>"
      SMTP_PORT: "<PLACEHOLDER>"
      SMTP_USERNAME: "<PLACEHOLDER>"
      SMTP_PASSWORD: "<PLACEHOLDER>"
      SMTP_FROM: "<PLACEHOLDER>"

      GOTENBERG_HOST: "gotenberg"
      GOTENBERG_PORT: "3000"

      EMAIL_AUTO_SUBJECT: "TRUE"

      SKIP_VERIFICATIONS: "FALSE"
      SHOW_BOOKMARKLET: "TRUE"

      VIRTUAL_HOST: "your-domain.tld"
      VIRTUAL_PORT: "80"

  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - global

networks:
  # Assumption made : network "global" is created beforehand
  # with            : docker network create global
  global:
    external: true
  osmond:
