version: '3'
services:
  osmond:
    image: mosswill/osmond:latest
    ports:
      - "443:443"
    volumes:
      - ./certificate.pem:/certificate.pem
      - ./key.pem:/key.pem
    environment:
      SSL_ENABLED: "TRUE"

      SERVER_HOST: "https://your-domain.tld"
      SERVER_PORT: "443"
      SERVER_SECRET: "<PLACEHOLDER>"

      DOWNLOAD_USER_AGENT: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"

      SMTP_HOST: "<PLACEHOLDER>"
      SMTP_PORT: "<PLACEHOLDER>"
      SMTP_USERNAME: "<PLACEHOLDER>"
      SMTP_PASSWORD: "<PLACEHOLDER>"
      SMTP_FROM: "<PLACEHOLDER>"

      EMAIL_AUTO_SUBJECT: "TRUE"

      SKIP_VERIFICATIONS: "FALSE"
      SHOW_BOOKMARKLET: "TRUE"

